version: '2'

services:
  app:
    build:
      context: docker
      dockerfile: app/app.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html:cached
      - ~/.composer/cache:/var/www/.composer/cache/:delegated
    ports:
      - 80:80
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  db:
    image: mysql:5.7
    volumes:
      # Named database data for persistence
      - dbdata:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=laravel_docker_root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel

volumes:
  dbdata:
